# Generated by Django 4.0.4 on 2022-09-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgers',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.group'),
        ),
    ]
