# Generated by Django 4.0.4 on 2022-09-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0002_ledgers_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='credit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='debit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='particularsby',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='particularsto',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
