# Generated by Django 4.0.4 on 2022-09-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0003_journal_credit_journal_debit_journal_particularsby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='particularsby',
        ),
    ]
