# Generated by Django 4.0.4 on 2022-09-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0004_remove_journal_particularsby'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
