# Generated by Django 4.0.4 on 2022-10-12 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0006_add_voucher_add_voucher2_add_voucher3_create_payhead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally_ledger',
            name='grp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.tally_group'),
        ),
    ]
