# Generated by Django 4.0.4 on 2022-10-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0007_tally_ledger_grp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='companies',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='books_begin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='currency_symbol',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='d_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='fax',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='fin_begin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='fin_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='formal_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='password',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgers_vouchers',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='mailing_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
