# Generated by Django 4.0.4 on 2022-10-14 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0008_months_companies_address_companies_books_begin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_closingbalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_group', models.IntegerField(null=True)),
                ('stock_item', models.IntegerField(null=True)),
                ('closing_balance', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='tally_ledger',
            name='closing_balance',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Ledger_vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particulars', models.CharField(max_length=225)),
                ('account', models.CharField(max_length=225, null=True)),
                ('voucher_type', models.CharField(max_length=225, null=True)),
                ('voucher_no', models.CharField(max_length=225)),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.tally_ledger')),
            ],
        ),
    ]
