# Generated by Django 4.0.4 on 2022-07-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0011_purchase_purchase_date_sales_sales_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='currentbalance',
            new_name='currentbalancep',
        ),
        migrations.AddField(
            model_name='sales',
            name='currentbalancesl',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
