# Generated by Django 4.0.4 on 2022-08-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0013_alter_sales_nameofitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='currentbalance',
            new_name='currentbalancep',
        ),
        migrations.AddField(
            model_name='purchase',
            name='currentbalancepl',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
