# Generated by Django 4.0.4 on 2022-08-03 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0014_rename_currentbalance_purchase_currentbalancep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.voucher'),
        ),
    ]
