# Generated by Django 4.0.4 on 2022-08-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0015_purchase_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(max_length=1000, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='sales',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(max_length=1000, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='nameofitem',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='currentbalancesl',
            field=models.IntegerField(max_length=225, null=True),
        ),
    ]
