# Generated by Django 4.0.4 on 2022-08-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0016_purchase_price_purchase_quantity_sales_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particularsby', models.CharField(max_length=225, null=True)),
                ('particularsto', models.CharField(max_length=225, null=True)),
                ('credit', models.IntegerField(default=0, null=True)),
                ('journalledger', models.CharField(max_length=225, null=True)),
                ('debit', models.IntegerField(default=0, null=True)),
                ('journal_date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='currentbalancesl',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
