# Generated by Django 4.0.4 on 2022-08-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0019_purchase_total_sales_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='company',
        ),
    ]
