# Generated by Django 4.0.4 on 2022-08-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0020_remove_voucher_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='voucher',
        ),
    ]
