# Generated by Django 4.0.4 on 2022-09-02 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0021_remove_purchase_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledgers_vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('voucher_type', models.CharField(max_length=225)),
                ('voucher_date', models.DateField(null=True)),
                ('ledger', models.CharField(max_length=225)),
                ('credit', models.IntegerField(default=0)),
                ('debit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.RemoveField(
            model_name='ledger_asset_rounding',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ledger_asset_rounding',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='ledger_asset_statutory',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ledger_asset_statutory',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='ledger_banking_details',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ledger_banking_details',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='ledger_mailing_details',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ledger_mailing_details',
            name='ledger',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='active',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='address4',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='books_begin',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='country',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='currency_symbol',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='fin_begin',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='formal_name',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='state',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='website',
        ),
        migrations.RemoveField(
            model_name='group',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='group',
            name='calculation',
        ),
        migrations.RemoveField(
            model_name='group',
            name='company',
        ),
        migrations.RemoveField(
            model_name='group',
            name='debit_credit',
        ),
        migrations.RemoveField(
            model_name='group',
            name='sub_ledger',
        ),
        migrations.RemoveField(
            model_name='group',
            name='under',
        ),
        migrations.RemoveField(
            model_name='group',
            name='used_purchase',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='pan_no',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='provide_banking_details',
        ),
        migrations.DeleteModel(
            name='Ledger_Asset_Rounding',
        ),
        migrations.DeleteModel(
            name='Ledger_Asset_Statutory',
        ),
        migrations.DeleteModel(
            name='Ledger_Banking_Details',
        ),
        migrations.DeleteModel(
            name='Ledger_Mailing_Details',
        ),
        migrations.AddField(
            model_name='subgroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.group'),
        ),
    ]
