# Generated by Django 4.0.4 on 2022-09-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0023_rename_voucher_date_ledgers_vouchers_ledgervoucher_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgers_vouchers',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.ledger'),
        ),
    ]
