# Generated by Django 4.0.4 on 2022-09-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0025_remove_ledgers_vouchers_alias_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ledger',
            new_name='Voucher',
        ),
        migrations.RenameField(
            model_name='ledgers_vouchers',
            old_name='ledger',
            new_name='Voucher',
        ),
        migrations.RemoveField(
            model_name='ledgers_vouchers',
            name='voucher_type',
        ),
    ]
