# Generated by Django 4.0.4 on 2022-09-02 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0026_rename_ledger_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgers_vouchers',
            name='SubGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.subgroup'),
        ),
    ]
