# Generated by Django 4.0.4 on 2022-09-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0029_ledgers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgers_vouchers',
            name='ledger',
        ),
    ]
