# Generated by Django 4.0.4 on 2022-09-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0030_remove_ledgers_vouchers_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgers_vouchers',
            name='ledgers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.ledgers'),
        ),
    ]
