# Generated by Django 4.0.4 on 2022-09-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0031_ledgers_vouchers_ledgers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgers_vouchers',
            name='closingbalance',
            field=models.IntegerField(default=0),
        ),
    ]
